'use client';
import Link from 'next/link'; import {useEffect,useState} from 'react'; import {useParams} from 'next/navigation'; import AppShell from '@/components/AppShell'; import StatusBadge from '@/components/StatusBadge'; import SectionCard from '@/components/SectionCard'; import EmptyState from '@/components/EmptyState'; import InvestigationPanel from '@/components/InvestigationPanel'; import {getTest,getTestHistory,getTestDecisions,getTestOutcomes} from '@/lib/api';
function label(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
export default function TestDetailsPage(){const params=useParams<{id:string}>();const id=String(params.id);const [test,setTest]=useState<any>(null);const [history,setHistory]=useState<any[]>([]);const [decisions,setDecisions]=useState<any[]>([]);const [outcomes,setOutcomes]=useState<any[]>([]);const [error,setError]=useState('');useEffect(()=>{Promise.all([getTest(id),getTestHistory(id),getTestDecisions(id),getTestOutcomes(id)]).then(([t,h,d,o])=>{setTest(t);setHistory(h);setDecisions(d);setOutcomes(o)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load test.'));},[id]); if(!test)return <AppShell>{error?<div className="notice-error">{error}</div>:<div className="section-card">Loading test…</div>}</AppShell>;return <AppShell><div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge value={test.status}/><span className="source-chip">{test.source||'demo'} data</span></div><h1 className="mt-3 text-3xl font-bold tracking-tight">{test.name}</h1><p className="mt-2 text-sm text-slate-500">{test.service} · {test.repository}</p></div><Link href="/tests" className="secondary-btn">← Back to tests</Link></div>
<div className="grid gap-4 md:grid-cols-4"><div className="mini-stat"><span>CI runs</span><b>{history.length}</b></div><div className="mini-stat"><span>Failures</span><b>{history.filter(r=>r.status==='failed').length}</b></div><div className="mini-stat"><span>Decisions</span><b>{decisions.length}</b></div><div className="mini-stat"><span>Outcomes</span><b>{outcomes.length}</b></div></div>
<section className="section-card" id="investigate"><div className="flex items-center justify-between"><div><p className="eyebrow">Investigation</p><h2 className="section-title">Understand before you quarantine</h2></div></div><InvestigationPanel testId={id}/></section>
<div className="grid gap-5 lg:grid-cols-2"><SectionCard title="CI history" eyebrow="Evidence">{history.length?<div className="space-y-2">{history.map((r:any)=><div key={r.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap items-center gap-2"><StatusBadge value={r.status}/><span className="text-xs text-slate-500">{new Date(r.timestamp).toLocaleString()}</span><span className="source-chip">{r.source||'demo'}</span></div><p className="mt-2 text-sm font-semibold">{r.workflow_name||r.job_name||r.commit_sha}</p>{r.error_message&&<p className="mt-1 text-xs leading-5 text-rose-700">{r.error_message}</p>}<div className="mt-2 text-[11px] text-slate-400">{r.failure_type?label(r.failure_type):'No failure type'} · {r.duration} ms</div></div>)}</div>:<EmptyState title="No CI history available" description="This test does not have runs in the current workspace."/>}</SectionCard>
<SectionCard title="Engineering decisions" eyebrow="Human in the loop">{decisions.length?<div className="space-y-2">{decisions.map((d:any)=><div key={d.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap items-center gap-2"><span className="source-chip">Agent: {label(d.agent_recommendation||'unknown')}</span><span className="source-chip">Human: {label(d.human_decision||'unknown')}</span></div><p className="mt-2 text-xs leading-5 text-slate-600">{d.human_reason||'No human reason recorded.'}</p></div>)}</div>:<EmptyState title="No decisions recorded" description="Investigate the test and record the engineer's decision."/>}</SectionCard>
</div>
<SectionCard title="Learned outcomes" eyebrow="Organizational memory">{outcomes.length?<div className="space-y-2">{outcomes.map((o:any)=><div key={o.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap items-center gap-2"><StatusBadge value={o.outcome}/><span className="text-xs text-slate-500">{new Date(o.timestamp).toLocaleString()}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{o.notes}</p></div>)}</div>:<EmptyState title="No learned outcomes yet" description="Record what actually happened after the human decision."/>}</SectionCard>
</div></AppShell>}
